apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: infra
data:
  datasource-prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.infra.svc:80
        isDefault: true

  dashboards-provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

  kubernetes-monitoring.json: |
    {
      "title": "Kubernetes Monitoring (Placeholder)",
      "schemaVersion": 38,
      "version": 1,
      "panels": []
    }
