replicaCount: 1

image:
  repository: gris24/bootcampclt-api
  tag: "1.0.2"
  pullPolicy: IfNotPresent

app:
  containerPort: 8080
  applicationName: BootcampCLT-API

service:
  type: NodePort
  port: 80
  targetPort: 8080

postgres:
  host: postgres-ngs
  port: 5432
  database: hardwareCLT
  username: postgres
  password: "a.123456"

seq:
  host: seq.infra.svc.cluster.local
  port: 5341
